// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3LGRcBiWLBZXoZGNYTbeXb1Ej3DjrIF0',
    appId: '1:269542624062:web:2d30c75f6f3a37b18bfa6f',
    messagingSenderId: '269542624062',
    projectId: 'chat-badd7',
    authDomain: 'chat-badd7.firebaseapp.com',
    storageBucket: 'chat-badd7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjs9WO3X6AsS7mRoYTPvgg_9dHuk0ypJw',
    appId: '1:269542624062:android:1762b050a033a6298bfa6f',
    messagingSenderId: '269542624062',
    projectId: 'chat-badd7',
    storageBucket: 'chat-badd7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO7RhStTpBskS7EFATh1E9UPHPWDHzDGw',
    appId: '1:269542624062:ios:a51ec3f3f1dadc6d8bfa6f',
    messagingSenderId: '269542624062',
    projectId: 'chat-badd7',
    storageBucket: 'chat-badd7.appspot.com',
    androidClientId: '269542624062-07tcdqlmn2q6rahmaj4c2rk4ss65en4d.apps.googleusercontent.com',
    iosClientId: '269542624062-lkq556i8n0vrgghu6661pc4r98nnicjl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO7RhStTpBskS7EFATh1E9UPHPWDHzDGw',
    appId: '1:269542624062:ios:a51ec3f3f1dadc6d8bfa6f',
    messagingSenderId: '269542624062',
    projectId: 'chat-badd7',
    storageBucket: 'chat-badd7.appspot.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3LGRcBiWLBZXoZGNYTbeXb1Ej3DjrIF0',
    appId: '1:269542624062:web:05fc6ebdf32decb98bfa6f',
    messagingSenderId: '269542624062',
    projectId: 'chat-badd7',
    authDomain: 'chat-badd7.firebaseapp.com',
    storageBucket: 'chat-badd7.appspot.com',
  );
}